default:
	g++ -std=c++17 -g -DONNX_ML=1 main.cpp -o main -I/home/kumarutkarsh/Desktop/mlpack-4.6.2/build/installdir/include -I./../../src -I./../../src/dag -larmadillo -lonnx_proto -lprotobuf
	./main
